# Generated by Django 2.2.16 on 2022-01-07 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Введите год в формате: <YYYY>', validators=[django.core.validators.MinValueValidator(1100), django.core.validators.MaxValueValidator(2022)], verbose_name='год'),
        ),
    ]
