# Generated by Django 2.2.16 on 2022-01-20 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20220119_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.PositiveSmallIntegerField(help_text='Введите год в формате: YYYY', verbose_name='год'),
        ),
    ]
